# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: ant design pro

trigger:
  - master

jobs:
  - job: lintAndBuild

    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        clean: false
      - script: yarn
        displayName: install
      - script: npm run build
        env:
          PROGRESS: none
        displayName: build
